/**
 * Core domain types for MobileNoteAssist.
 */

/**
 * Note geometry + body, in **original-image pixel space** (the same
 * space Danbooru's `/notes` API uses). The renderer projects to the
 * current display rect via `imageToScreenRect`; tap handlers project
 * the other way via `screenToImageRect`. Display-space numbers never
 * enter a `NoteState`.
 */
export interface NoteState {
  /** Original-image x-coord of the box top-left. */
  x: number;
  /** Original-image y-coord of the box top-left. */
  y: number;
  /** Original-image width. */
  w: number;
  /** Original-image height. */
  h: number;
  /** Note body. */
  text: string;
}

declare const NOTE_ID_BRAND: unique symbol;

/**
 * Server-loaded note id (numeric Danbooru id stringified, e.g. `'12345'`).
 * Confirm-phase routing sends these via PUT (edits) or DELETE (soft-deletes).
 *
 * The brand is a phantom type — at runtime this is a plain `string`. Branding
 * exists to make accidental mixing with `TempNoteId` or unbranded `string`
 * a compile-time error at routing/persistence sites.
 */
export type ServerNoteId = string & {readonly [NOTE_ID_BRAND]: 'server'};

/**
 * Temp note id (`temp-<uuid>`), generated by `genNoteId` for boxes the user
 * created in active mode but hasn't yet ✔'d through Confirm. POST routes
 * these to the server, after which the local entry is re-keyed with the
 * server-assigned `ServerNoteId` (`applyServerStateToLocal`).
 */
export type TempNoteId = string & {readonly [NOTE_ID_BRAND]: 'temp'};

/**
 * Union of both id flavors. Most code paths treat all notes uniformly and
 * accept the union; sites that branch on origin (Confirm classification,
 * actionLog inversion of `create`) narrow via `isTempNoteId`/`isServerNoteId`.
 */
export type NoteId = ServerNoteId | TempNoteId;

/** Cast a server-side numeric or string id to `ServerNoteId`. Use at the
 *  trust boundary where server responses enter the local store. */
export function asServerNoteId(id: number | string): ServerNoteId {
  return String(id) as ServerNoteId;
}

/** Cast a freshly minted `temp-<uuid>` string to `TempNoteId`. Use only
 *  inside `genNoteId` — every other caller should accept `TempNoteId`
 *  by type and never construct one directly. */
export function asTempNoteId(s: string): TempNoteId {
  return s as TempNoteId;
}

/** Type guard — true for ids minted by `genNoteId`. The runtime check is
 *  the literal `temp-` prefix, which `asTempNoteId` is the sole producer of. */
export function isTempNoteId(id: NoteId): id is TempNoteId {
  return id.startsWith('temp-');
}

/** Type guard — true for ids that came from the server (anything not
 *  prefixed `temp-`). Complement of `isTempNoteId`. */
export function isServerNoteId(id: NoteId): id is ServerNoteId {
  return !id.startsWith('temp-');
}

/**
 * A note in the in-memory collection (`notes: Map<NoteId, Note>`).
 * Both server-loaded and temp notes share this shape.
 */
export interface Note {
  /** Live working state, mutated by edits. */
  current: NoteState;
  /**
   * Immutable snapshot at create/load time. The dirty (green)
   * classification compares against this.
   */
  initialState: NoteState;
  /**
   * Latest popover-✔ checkpoint. The ✖ button reverts `current`
   * here, and per-note Undo restores from here (with `actionLog`
   * providing the multi-step history).
   */
  confirmedState: NoteState;
  /**
   * Soft-delete flag. The box is kept in the collection (so undo
   * can restore it) and shown with red-dashed styling until Confirm
   * runs.
   */
  isDeleted: boolean;
  /**
   * True for notes loaded from the server when active mode is
   * entered. Drives Confirm-phase routing: POST for new temps,
   * PUT for edited server notes, DELETE for soft-deleted server
   * notes.
   */
  isServerNote: boolean;
  /**
   * True after the first popoverConfirm for this note.
   * Distinguishes "fresh new" notes (popover-dismiss hard-deletes —
   * cancel creation) from already-committed notes (popover-dismiss
   * reverts to `confirmedState` — cancel edits). Inferring this
   * from `confirmedState === initialState` would falsely classify
   * "user ✔'d an empty box without editing" as fresh-new.
   */
  everConfirmed: boolean;
  /** The `.dmna-note-box` div, or `null` until first render. */
  domElement: HTMLElement | null;
}

/**
 * Per-note action log entry. The action log is a `Map<NoteId, ActionLogEntry[]>`
 * driving per-note Undo (popover ↶, Wave 3.5+). `popoverUndo` finds the
 * latest entry matching the note and reverses it.
 *
 * Discriminated by `type`:
 * - `'create'`    — new temp note spawned. `prevState` is `null` (the
 *                   note didn't exist yet); undo hard-deletes the note.
 * - `'edit'`      — ✔ checkpoint. `prevState` is the prior
 *                   `confirmedState`; undo restores both `current` and
 *                   `confirmedState` (✔ commits both, so undo reverts
 *                   both).
 * - `'delete'`    — 🗑 soft-delete. `prevState` is `current` at delete
 *                   time; undo flips `isDeleted=false` and restores
 *                   `current`.
 * - `'transform'` — drag/resize gesture finished with movement.
 *                   `prevState` is `current` at gesture start; undo
 *                   restores only geometry (`x/y/w/h`), leaving `text`
 *                   and `confirmedState` alone. Drag doesn't change
 *                   `confirmedState`, so resetting would clobber a
 *                   prior ✔; typing after a drag shouldn't be undone
 *                   by a ↶ aimed at the drag.
 */
export type ActionLogEntry =
  | {noteId: NoteId; type: 'create'; prevState: null}
  | {noteId: NoteId; type: 'edit'; prevState: NoteState}
  | {noteId: NoteId; type: 'delete'; prevState: NoteState}
  | {noteId: NoteId; type: 'transform'; prevState: NoteState};

/**
 * High-level interaction mode.
 *
 * - `'idle'`   — script off. Boxes hidden, image is plain, floating
 *                button shows the default 📝 icon.
 * - `'active'` — editing enabled. Server notes (if any) loaded as
 *                boxes; taps on the image create new ones, taps on
 *                existing boxes activate them, and the popover offers
 *                ✔ / ✖ / 🗑.
 *
 * Toggled by the arc menu's Edit item; turned off via three paths
 * (PLAN Z11): floating-button double-tap, menu re-tap of Edit, or
 * post-Confirm reload (Phase 4).
 */
export type Mode = 'idle' | 'active';

/**
 * Box visual state — drives the 4-color priority used by `renderNoteBox`.
 * Priority (highest → lowest): active > deleted > dirty > default.
 *
 * - `'active'`  — currently focused note (popover open). Orange.
 * - `'deleted'` — soft-deleted (`isDeleted: true`). Red dashed.
 * - `'dirty'`   — `current` differs from `initialState`. Green.
 * - `'default'` — clean, unfocused, server-original. Blue.
 *
 * (The actual fill/border colors live in `src/styles.ts`; this comment
 * is the canonical name-to-color mapping for cross-referencing the
 * user-facing manual in README.md.)
 */
export type BoxState = 'active' | 'deleted' | 'dirty' | 'default';

/**
 * Rectangle in either display space or image space — the helpers that
 * project between the two (`imageToScreenRect`, `screenToImageRect`)
 * accept and return this shape. `text` is intentionally absent: this
 * is a geometry-only carrier, decoupled from `NoteState`.
 */
export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * Tag-popover delta (PLAN.md D9). Returned by `ui/tag-popover.
 * showTagPopover` and consumed by `confirm/batch.sendBatch`. Lives
 * in types.ts because both modules reference it; otherwise the
 * ui→confirm same-layer import would couple unnecessarily.
 *
 * `null` (returned by showTagPopover, not modeled here) means the
 * user canceled — caller aborts the entire Confirm flow.
 */
export interface TagDelta {
  tagsToAdd: string[];
  tagsToRemove: string[];
}
